import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { 
    DietPlan, DietPlanItem, WorkoutPlan, WorkoutPlanItem, 
    DAY_LABELS, MEAL_TYPES 
} from "./dietWorkoutService";

// Extend jsPDF type for autotable
interface jsPDFWithAutoTable extends jsPDF {
    lastAutoTable: {
        finalY: number;
    };
}

export const pdfExportService = {
    
    /**
     * Export a Diet Plan to PDF
     */
    async exportDietPlan(plan: DietPlan, gymName: string) {
        const doc = new jsPDF() as jsPDFWithAutoTable;
        const pageWidth = doc.internal.pageSize.getWidth();

        // 1. Header
        doc.setFontSize(22);
        doc.setTextColor(40, 44, 52);
        doc.text(gymName.toUpperCase(), pageWidth / 2, 20, { align: "center" });
        
        doc.setFontSize(16);
        doc.setTextColor(100);
        doc.text("PERSONALIZED DIET PLAN", pageWidth / 2, 30, { align: "center" });

        // 2. Plan Info
        doc.setFontSize(11);
        doc.setTextColor(0);
        doc.text(`Title: ${plan.title}`, 14, 45);
        doc.text(`Member: ${plan.gym_members?.full_name || "N/A"}`, 14, 52);
        doc.text(`Trainer: ${plan.gym_staff?.full_name || "N/A"}`, 14, 59);
        doc.text(`Duration: ${format(new Date(plan.start_date), "MMM d, yyyy")} - ${format(new Date(plan.end_date), "MMM d, yyyy")}`, 14, 66);
        
        if (plan.notes) {
            doc.setFontSize(10);
            doc.setTextColor(80);
            const splitNotes = doc.splitTextToSize(`Notes: ${plan.notes}`, pageWidth - 28);
            doc.text(splitNotes, 14, 75);
        }

        let currentY = plan.notes ? 85 : 75;

        // 3. Items (Day by Day)
        const items = plan.gym_diet_plan_items || [];
        
        for (let day = 1; day <= 7; day++) {
            const dayItems = items.filter(i => i.day_of_week === day);
            if (dayItems.length === 0) continue;

            // Check page overflow
            if (currentY > 250) {
                doc.addPage();
                currentY = 20;
            }

            doc.setFontSize(12);
            doc.setTextColor(33, 150, 243); // Primary color
            
            const totalCals = dayItems.reduce((acc, i) => acc + (i.calories || 0), 0);
            const dayText = totalCals > 0 
                ? `${DAY_LABELS[day].toUpperCase()} (${totalCals} KCAL)`
                : DAY_LABELS[day].toUpperCase();
                
            doc.text(dayText, 14, currentY);
            currentY += 5;

            const tableData = dayItems.map(item => [
                MEAL_TYPES.find(m => m.value === item.meal_type)?.label || item.meal_type,
                item.food_item,
                item.quantity || "-",
                item.calories || "-",
                `${item.protein || "-"}/${item.carbs || "-"}/${item.fat || "-"}`,
                item.notes || "-"
            ]);

            autoTable(doc, {
                startY: currentY,
                head: [['Meal', 'Food Item', 'Qty', 'Cals', 'P/C/F', 'Notes']],
                body: tableData,
                theme: 'striped',
                headStyles: { fillColor: [33, 150, 243], textColor: [255, 255, 255] },
                margin: { left: 14, right: 14 },
                styles: { fontSize: 9 }
            });

            currentY = (doc as any).lastAutoTable.finalY + 12;
        }

        // 4. Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Generated by FitFlow - Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
        }

        doc.save(`${plan.gym_members?.full_name}_Diet_Plan_${format(new Date(), "yyyy-MM-dd")}.pdf`);
    },

    /**
     * Export a Workout Plan to PDF
     */
    async exportWorkoutPlan(plan: WorkoutPlan, gymName: string) {
        const doc = new jsPDF() as jsPDFWithAutoTable;
        const pageWidth = doc.internal.pageSize.getWidth();

        // 1. Header
        doc.setFontSize(22);
        doc.setTextColor(40, 44, 52);
        doc.text(gymName.toUpperCase(), pageWidth / 2, 20, { align: "center" });
        
        doc.setFontSize(16);
        doc.setTextColor(100);
        doc.text("PERSONALIZED WORKOUT PLAN", pageWidth / 2, 30, { align: "center" });

        // 2. Plan Info
        doc.setFontSize(11);
        doc.setTextColor(0);
        doc.text(`Title: ${plan.title}`, 14, 45);
        doc.text(`Member: ${plan.gym_members?.full_name || "N/A"}`, 14, 52);
        doc.text(`Trainer: ${plan.gym_staff?.full_name || "N/A"}`, 14, 59);
        doc.text(`Duration: ${format(new Date(plan.start_date), "MMM d, yyyy")} - ${format(new Date(plan.end_date), "MMM d, yyyy")}`, 14, 66);
        
        if (plan.notes) {
            doc.setFontSize(10);
            doc.setTextColor(80);
            const splitNotes = doc.splitTextToSize(`Notes: ${plan.notes}`, pageWidth - 28);
            doc.text(splitNotes, 14, 75);
        }

        let currentY = plan.notes ? 85 : 75;

        // 3. Items (Day by Day)
        const items = plan.gym_workout_plan_items || [];
        
        for (let day = 1; day <= 7; day++) {
            const dayItems = items.filter(i => i.day_of_week === day);
            if (dayItems.length === 0) continue;

            if (currentY > 250) {
                doc.addPage();
                currentY = 20;
            }

            doc.setFontSize(12);
            doc.setTextColor(233, 30, 99); // Pink-ish color for workouts
            
            const muscles = Array.from(new Set(dayItems.map(i => i.muscle_group).filter(Boolean))).join(", ");
            const dayText = muscles 
                ? `${DAY_LABELS[day].toUpperCase()} (${muscles.toUpperCase()})`
                : DAY_LABELS[day].toUpperCase();

            doc.text(dayText, 14, currentY);
            currentY += 5;

            const tableData = dayItems.map(item => [
                item.exercise_name,
                item.muscle_group || "-",
                item.sets || "-",
                item.reps || "-",
                item.weight || "-",
                item.rest_period || "-",
                item.notes || "-"
            ]);

            autoTable(doc, {
                startY: currentY,
                head: [['Exercise', 'Muscle', 'Sets', 'Reps', 'Weight', 'Rest', 'Notes']],
                body: tableData,
                theme: 'striped',
                headStyles: { fillColor: [233, 30, 99], textColor: [255, 255, 255] },
                margin: { left: 14, right: 14 },
                styles: { fontSize: 8 }
            });

            currentY = (doc as any).lastAutoTable.finalY + 12;
        }

        // 4. Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Generated by FitFlow - Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
        }

        doc.save(`${plan.gym_members?.full_name}_Workout_Plan_${format(new Date(), "yyyy-MM-dd")}.pdf`);
    }
};
