import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { 
    DietPlan, DietPlanItem, WorkoutPlan, WorkoutPlanItem, 
    DAY_LABELS, MEAL_TYPES 
} from "./dietWorkoutService";

// Extend jsPDF type for autotable
interface jsPDFWithAutoTable extends jsPDF {
    lastAutoTable: {
        finalY: number;
    };
}

export const pdfExportService = {
    
    /**
     * Export a Diet Plan to PDF
     */
    async exportDietPlan(plan: DietPlan, gymName: string) {
        const doc = new jsPDF() as jsPDFWithAutoTable;
        const pageWidth = doc.internal.pageSize.getWidth();

        // 1. Header
        doc.setFontSize(22);
        doc.setTextColor(40, 44, 52);
        doc.text(gymName.toUpperCase(), pageWidth / 2, 20, { align: "center" });
        
        doc.setFontSize(16);
        doc.setTextColor(100);
        doc.text("PERSONALIZED DIET PLAN", pageWidth / 2, 30, { align: "center" });

        // 2. Plan Info
        doc.setFontSize(11);
        doc.setTextColor(0);
        doc.text(`Title: ${plan.title}`, 14, 45);
        doc.text(`Member: ${plan.gym_members?.full_name || "N/A"}`, 14, 52);
        doc.text(`Staff: ${plan.gym_staff?.full_name || "N/A"}`, 14, 59);
        doc.text(`Duration: ${format(new Date(plan.start_date), "MMM d, yyyy")} - ${format(new Date(plan.end_date), "MMM d, yyyy")}`, 14, 66);
        
        if (plan.notes) {
            doc.setFontSize(10);
            doc.setTextColor(80);
            const splitNotes = doc.splitTextToSize(`Notes: ${plan.notes}`, pageWidth - 28);
            doc.text(splitNotes, 14, 75);
        }

        let currentY = plan.notes ? 85 : 75;

        // 3. Items (Day by Day)
        const items = plan.gym_diet_plan_items || [];
        
        for (let day = 1; day <= 7; day++) {
            const dayItems = items.filter(i => i.day_of_week === day);
            if (dayItems.length === 0) continue;

            // Check page overflow
            if (currentY > 250) {
                doc.addPage();
                currentY = 20;
            }

            doc.setFontSize(12);
            doc.setTextColor(33, 150, 243); // Primary color
            
            const totalCals = dayItems.reduce((acc, i) => acc + (i.calories || 0), 0);
            const dayText = totalCals > 0 
                ? `${DAY_LABELS[day].toUpperCase()} (${totalCals} KCAL)`
                : DAY_LABELS[day].toUpperCase();
                
            doc.text(dayText, 14, currentY);
            currentY += 5;

            const tableData = dayItems.map(item => [
                MEAL_TYPES.find(m => m.value === item.meal_type)?.label || item.meal_type,
                item.food_item,
                item.quantity || "-",
                item.calories || "-",
                `${item.protein || "-"}/${item.carbs || "-"}/${item.fat || "-"}`,
                item.notes || "-"
            ]);

            autoTable(doc, {
                startY: currentY,
                head: [['Meal', 'Food Item', 'Qty', 'Cals', 'P/C/F', 'Notes']],
                body: tableData,
                theme: 'striped',
                headStyles: { fillColor: [33, 150, 243], textColor: [255, 255, 255] },
                margin: { left: 14, right: 14 },
                styles: { fontSize: 9 }
            });

            currentY = (doc as any).lastAutoTable.finalY + 12;
        }

        // 4. Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Generated by Gymatrix - Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
        }

        doc.save(`${plan.gym_members?.full_name}_Diet_Plan_${format(new Date(), "yyyy-MM-dd")}.pdf`);
    },

    /**
     * Export a Workout Plan to PDF
     */
    async exportWorkoutPlan(plan: WorkoutPlan, gymName: string) {
        const doc = new jsPDF() as jsPDFWithAutoTable;
        const pageWidth = doc.internal.pageSize.getWidth();

        // 1. Header
        doc.setFontSize(22);
        doc.setTextColor(40, 44, 52);
        doc.text(gymName.toUpperCase(), pageWidth / 2, 20, { align: "center" });
        
        doc.setFontSize(16);
        doc.setTextColor(100);
        doc.text("PERSONALIZED WORKOUT PLAN", pageWidth / 2, 30, { align: "center" });

        // 2. Plan Info
        doc.setFontSize(11);
        doc.setTextColor(0);
        doc.text(`Title: ${plan.title}`, 14, 45);
        doc.text(`Member: ${plan.gym_members?.full_name || "N/A"}`, 14, 52);
        doc.text(`Staff: ${plan.gym_staff?.full_name || "N/A"}`, 14, 59);
        doc.text(`Duration: ${format(new Date(plan.start_date), "MMM d, yyyy")} - ${format(new Date(plan.end_date), "MMM d, yyyy")}`, 14, 66);
        
        if (plan.notes) {
            doc.setFontSize(10);
            doc.setTextColor(80);
            const splitNotes = doc.splitTextToSize(`Notes: ${plan.notes}`, pageWidth - 28);
            doc.text(splitNotes, 14, 75);
        }

        let currentY = plan.notes ? 85 : 75;

        // 3. Items (Day by Day)
        const items = plan.gym_workout_plan_items || [];
        
        for (let day = 1; day <= 7; day++) {
            const dayItems = items.filter(i => i.day_of_week === day);
            if (dayItems.length === 0) continue;

            if (currentY > 250) {
                doc.addPage();
                currentY = 20;
            }

            doc.setFontSize(12);
            doc.setTextColor(233, 30, 99); // Pink-ish color for workouts
            
            const muscles = Array.from(new Set(dayItems.map(i => i.muscle_group).filter(Boolean))).join(", ");
            const dayText = muscles 
                ? `${DAY_LABELS[day].toUpperCase()} (${muscles.toUpperCase()})`
                : DAY_LABELS[day].toUpperCase();

            doc.text(dayText, 14, currentY);
            currentY += 5;

            const tableData = dayItems.map(item => [
                item.exercise_name,
                item.muscle_group || "-",
                item.sets || "-",
                item.reps || "-",
                item.weight || "-",
                item.rest_period || "-",
                item.notes || "-"
            ]);

            autoTable(doc, {
                startY: currentY,
                head: [['Exercise', 'Muscle', 'Sets', 'Reps', 'Weight', 'Rest', 'Notes']],
                body: tableData,
                theme: 'striped',
                headStyles: { fillColor: [233, 30, 99], textColor: [255, 255, 255] },
                margin: { left: 14, right: 14 },
                styles: { fontSize: 8 }
            });

            currentY = (doc as any).lastAutoTable.finalY + 12;
        }

        // 4. Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Generated by Gymatrix - Page ${i} of ${pageCount}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
        }

        doc.save(`${plan.gym_members?.full_name}_Workout_Plan_${format(new Date(), "yyyy-MM-dd")}.pdf`);
    },

    /**
     * Export a Subscription Invoice to PDF
     */
    async exportInvoice(data: any, gymName: string) {
        const { invoice, customer, items } = data;
        const doc = new jsPDF() as jsPDFWithAutoTable;
        const pageWidth = doc.internal.pageSize.getWidth();
        const primaryColor: [number, number, number] = [15, 23, 42]; // Slate-900

        // 1. Header & Logo area
        doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.rect(0, 0, pageWidth, 40, 'F');
        
        doc.setFontSize(24);
        doc.setTextColor(255, 255, 255);
        doc.setFont("helvetica", "bold");
        doc.text("INVOICE", 14, 27);

        doc.setFontSize(14);
        doc.text(String(gymName || "GYMATRIX").toUpperCase(), pageWidth - 14, 27, { align: "right" });

        // 2. Invoice Details Row
        doc.setTextColor(0);
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        
        // Left Side: Bill To
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("BILL TO:", 14, 55);
        
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.text(String(customer.name || "Valued Customer"), 14, 62);
        doc.setTextColor(100);
        doc.text(String(customer.email || "N/A"), 14, 67);

        // Right Side: Details
        doc.setTextColor(0);
        doc.setFont("helvetica", "bold");
        doc.text("INVOICE NO:", pageWidth - 80, 55);
        doc.setFont("helvetica", "normal");
        doc.text(String(invoice.number || "N/A"), pageWidth - 14, 55, { align: "right" });

        doc.setFont("helvetica", "bold");
        doc.text("DATE:", pageWidth - 80, 62);
        doc.setFont("helvetica", "normal");
        doc.text(format(new Date(invoice.date), "MMM d, yyyy"), pageWidth - 14, 62, { align: "right" });

        doc.setFont("helvetica", "bold");
        doc.text("PAYMENT:", pageWidth - 80, 69);
        doc.setFont("helvetica", "normal");
        doc.text(String(invoice.payment_method || "N/A").toUpperCase(), pageWidth - 14, 69, { align: "right" });

        // 3. Items Table
        const tableData = items.map((item: any) => [
            `${item.name}\n${item.description}`,
            `INR ${item.amount.toLocaleString()}`
        ]);

        autoTable(doc, {
            startY: 85,
            head: [[
                { content: 'Item / Description', styles: { halign: 'left' } },
                { content: 'Amount', styles: { halign: 'right' } }
            ]],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: primaryColor, textColor: [255, 255, 255] },
            margin: { left: 14, right: 14 },
            styles: { fontSize: 10, cellPadding: 5 },
            columnStyles: {
                0: { cellWidth: 'auto', halign: 'left' },
                1: { cellWidth: 50, halign: 'right' }
            }
        });

        const finalY = (doc as any).lastAutoTable.finalY + 15;

        // 4. Summary
        doc.setDrawColor(200);
        doc.line(pageWidth - 80, finalY, pageWidth - 14, finalY);
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.text("TOTAL PAID:", pageWidth - 80, finalY + 10);
        doc.text(`INR ${invoice.amount.toLocaleString()}`, pageWidth - 14, finalY + 10, { align: "right" });

        // 5. Footer
        doc.setTextColor(150);
        doc.setFontSize(9);
        doc.setFont("helvetica", "italic");
        doc.text("Thank you for your business!", pageWidth / 2, doc.internal.pageSize.getHeight() - 25, { align: "center" });
        
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.text("Gymatrix - Gym Management Simplified", pageWidth / 2, doc.internal.pageSize.getHeight() - 15, { align: "center" });

        const fileName = (invoice.number || "0000").replace(/[/\\?%*:|"<>]/g, '-');
        doc.save(`Invoice_${fileName}.pdf`);
    },

    /**
     * Export a General Report to PDF
     */
    async exportReport(data: {
        title: string,
        subtitle?: string,
        summary?: {
            title: string,
            headers: string[],
            rows: any[][]
        },
        details?: {
            title: string,
            headers: string[],
            rows: any[][]
        }
    }, gymName: string) {
        const doc = new jsPDF() as jsPDFWithAutoTable;
        const pageWidth = doc.internal.pageSize.getWidth();
        const primaryColor: [number, number, number] = [15, 23, 42]; // Slate-900

        // 1. Header
        doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        doc.rect(0, 0, pageWidth, 40, 'F');
        
        doc.setFontSize(20);
        doc.setTextColor(255, 255, 255);
        doc.setFont("helvetica", "bold");
        doc.text(data.title.toUpperCase(), 14, 25);

        doc.setFontSize(12);
        doc.text(String(gymName || "GYMATRIX").toUpperCase(), pageWidth - 14, 25, { align: "right" });

        if (data.subtitle) {
            doc.setFontSize(10);
            doc.setFont("helvetica", "normal");
            doc.text(data.subtitle, 14, 33);
        }

        let currentY = 50;

        // 2. Summary Table
        if (data.summary && data.summary.rows.length > 0) {
            doc.setTextColor(0);
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.text(data.summary.title, 14, currentY);
            currentY += 8;

            autoTable(doc, {
                startY: currentY,
                head: [data.summary.headers],
                body: data.summary.rows,
                theme: 'striped',
                headStyles: { fillColor: primaryColor, textColor: [255, 255, 255] },
                margin: { left: 14, right: 14 },
                styles: { fontSize: 10 }
            });

            currentY = (doc as any).lastAutoTable.finalY + 15;
        }

        // 3. Details Table
        if (data.details && data.details.rows.length > 0) {
            // Check for new page if close to bottom
            if (currentY > 250) {
                doc.addPage();
                currentY = 20;
            }

            doc.setTextColor(0);
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.text(data.details.title, 14, currentY);
            currentY += 8;

            autoTable(doc, {
                startY: currentY,
                head: [data.details.headers],
                body: data.details.rows,
                theme: 'striped',
                headStyles: { fillColor: primaryColor, textColor: [255, 255, 255] },
                margin: { left: 14, right: 14 },
                styles: { fontSize: 9 }
            });
        }

        // 4. Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Generated by Gymatrix - Page ${i} of ${pageCount} - ${format(new Date(), "PPpp")}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
        }

        const fileName = data.title.toLowerCase().replace(/\s+/g, '_');
        doc.save(`${fileName}_${format(new Date(), "yyyy-MM-dd")}.pdf`);
    }
};
